# Site settings
title: Office of Evaluation Sciences
description: The Office of Evaluation Sciences (OES) is a team of applied experts based at the General Services Administration (GSA) that combines academic expertise with experience implementing and evaluating evidence-based program changes to quickly learn what works, what works best, and what does not work.
url: "https://oes.gsa.gov" # the base hostname & protocol for your site
logo: /assets/img/logos/logo-name.png
feature_image: /assets/img/Kites-small.jpg
permalink: pretty

# Site theme
theme: uswds-jekyll

# Styles
styles:
  - /assets/css/main.css

# Collections
collections:
  projects:
    output: true
  team:
    output: true
  collaborations:
    output: true
  portfolios:
    output: true
 posts:
    output: true

defaults:
  - scope:
      path: ''
      type: projects
    values:
      layout: project-single
  - scope:
      path: ''
      type: team
    values:
      layout: team-single
  - scope:
      path: ''
      type: collaborations
    values:
      layout: collaboration-single
  - scope:
      path: ''
      type: portfolios
    values:
      layout: portfolio
  - scope:
      path: ''
      type: posts
    values:
      layout: post

colors:
  primary: '#0071bc'

# Google Analytics and DAP
analytics:
  google:
    code: 'UA-67580537-1'
  dap:
    agency: GSA
    subagency: OES

# Search.gov configuration
search_site_handle: oes.gsa.gov

footer:
  image: /assets/img/icons/gsa-white.svg
  email: oes@gsa.gov
  twitter:
    - usgsa
  text:

forms:
- type: newsletter
  privacypolicy:
    name: GSA Privacy and Security Notice
    url: https://gsa.gov
  fields:
    - type: hidden
      name: fbzx
      value: -7861934959779167198


# Build settings
include:
  - _navigation.json
exclude:
  - CONTRIBUTING.md
  - LICENSE.md
  - README.md
  - Gemfile
  - Gemfile.lock
